 name: Build and Push Docker Image

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.Virsat_82 }}" | docker login -u "${{ secrets.renugadevibalaji }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build . -t ${{ secrets.cicd_assignment }}/my-image:${{ github.sha }}
          docker push ${{ secrets.cicd_assignment }}/my-image:${{ github.sha }}
