 name: Build and Push Docker Image

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build . -t ${{ secrets.REGISTRY_USERNAME }}/my-image:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_USERNAME }}/my-image:${{ github.sha }}
Workflow 2: Pull and Run Docker Image
